### ISSUE TITLE
Добавить новые каналы (потоки ниже)

### ISSUE THREAD

**Issue by TaurerMedia** [smolnp/IPTVru#11]
Groovezzo: https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/7.m3u8
Криминал и Полиция: https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/5.m3u8
NINJA: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/3.m3u8
RRTV Europe: https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/6.m3u8
World-1: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/7.m3u8
KidsPlanet: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/4.m3u8
KidsPlanet+: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/2.m3u8
Quality HD: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/6.m3u8
Кулинар HD: https://nl2.live-stream.plus.taurer.org:443/RuCsPSXGYe/DgFExKzqEw/14.m3u8
Sunset Movie: https://stream.sunset-media.ru:443/Free/Free/1.m3u8
Sunset Space: https://stream.sunset-media.ru:443/Free/Free/3.m3u8
Sunset Music: https://stream.sunset-media.ru:443/Free/Free/2.m3u8
Sunset Kids: https://stream.sunset-media.ru:443/Free/Free/4.m3u8

**Comment by smolnp** [comment]
НЕ РАБОТАЮТ: 
Криминал и Полиция: [https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/5.m3u8](https://nl1.live-stream.plus.taurer.org/pbuPAuthGp/MDTTv32fbk/5.m3u8)
RRTV Europe: [https://nl1.live-stream.plus.taurer.org:443/pbuPAuthGp/MDTTv32fbk/6.m3u8](https://nl1.live-stream.plus.taurer.org/pbuPAuthGp/MDTTv32fbk/6.m3u8)
К остальным не нашёл программу передач. Если знаете, где взять к ним epg файл со значками и программой, скиньте ссылку. Значки и программа — обязательные условия для добавления телеканала в плейлист.

**Comment by smolnp** [comment]
Сейчас в сообществе проводится опрос, возможно некоторые каналы будут добавлены

**Comment by TaurerMedia** [comment]
Здравствуйте, новый канал от медиахолдинга:

LIVE:Полицейский с Рублевки
Ссылка: https://nl2.live-stream.plus.taurer.org/RuCsPSXGYe/DgFExKzqEw/15.m3u8
Пикон (будет доступен в течении недели): https://tv.taurer.org/iptv_content/logos/LVPOLICE_TEMP.png
