### ISSUE TITLE
IPtv-n.m3u

### ISSUE THREAD

**Issue by mistrwest** [smolnp/IPTVru#15]
#EXTM3U url-tvg="http://epg.it999.ru/ru2.xml.gz, https://iptvx.one/epg/epg.xml.gz" tvg-shift="+3" abs="true"

#EXTINF:-1 tvg-id="sony-turbo" tvg-logo="https://epg.one/img2/2803.png" group-title="Развлекательные",Russian Extreme Ultra
http://31.131.136.4:8001/play/e010
#EXTINF:-1 tvg-id="premialnoe-hd" tvg-logo="http://epg.one/img2/2732.png" group-title="Кинозал",Премиальное HD
http://31.131.136.4:8001/play/e011
#EXTINF:-1 tvg-id="ostrosiuzhetnoe-hd" tvg-logo="http://epg.one/img2/1588.png"(http://epg.one/img2/1588.png) group-title="Кинозал",Остросюжетное HD
http://31.131.136.4:8001/play/e012
#EXTINF:-1 tvg-id="sony-turbo" tvg-logo="http://epg.one/img2/2309.png" group-title="Кинозал",Шокирующее HD
http://31.131.136.4:8001/play/e013
#EXTINF:-1 tvg-id="komedijnoe-hd" tvg-logo="http://epg.one/img2/138.png" group-title="Кинозал",Комедийное HD
http://31.131.136.4:8001/play/e014

http://188.113.190.15/88/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2782" tvg-logo="http://epg.one/img2/2782.png" group-title="Спортивные",Футбол (EDTV 576p)
http://188.113.190.15/105/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2054" tvg-logo="http://epg.one/img2/2054.png" group-title="Спортивные",Матч! Боец (EDTV 576p)
http://188.113.190.15/126/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="1038" tvg-logo="http://epg.one/img2/1038.png" group-title="Спортивные",KHL Prime HD
http://188.113.190.15/116/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="3792" tvg-logo="https://epg.one/img2/3792.png" group-title="Спортивные",FightBox
http://188.113.190.15/147/tracks-v1a1/index.m3u8

#EXTINF:-1 tvg-id="7314" tvg-logo="http://epg.one/img2/7314.png" group-title="Кинозал",Кинеко HD
http://188.113.190.15/156/tracks-v1a1/index.m3u8

#EXTINF:-1 tvg-id="bridge-tv" tvg-logo="http://epg.one/img2/8803.png" group-title="Музыкальные",Bridge TV Фрэш (EDTV 576p)
#EXTINF:-1 tvg-id="Music Box Russia" tvg-logo="http://epg.one/img2/8803.png" group-title="Музыкальные",Music Box Russia (EDTV 576p)
http://188.113.190.15/158/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2412" tvg-logo="http://epg.one/img2/2412.png" group-title="Музыкальные",о2тв (EDTV 576p)
http://188.113.190.15/189/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="382" tvg-logo="http://epg.one/img2/382.png" group-title="Музыкальные",MTV Live HD
http://stream01.vnet.am/Channel_117/mono.m3u8

#EXTINF:-1 tvg-id="2443" tvg-logo="http://epg.one/img2/2443.png" group-title="Развлекательные",Драйв(EDTV 576p)
http://188.113.190.15/68/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2450" tvg-logo="https://epg.one/img2/2450.png" group-title="Развлекательные",Психология 21 (EDTV 576p)
http://188.113.190.15/73/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2451" tvg-logo="http://epg.one/img2/2451.png" group-title="Развлекательные",Вопросы и ответы (EDTV 576p)
http://188.113.190.15/74/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="Solnce-tv" tvg-logo="http://epg.one/img2/2308.png" group-title="Развлекательные",Москва Доверие (EDTV 576p)
http://188.113.190.15/86/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2450" tvg-logo="http://epg.one/img2/2362.png" group-title="Развлекательные",FUN BOX HD (EDTV 576p)
http://188.113.190.15/208/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2450" tvg-logo="http://epg.one/img2/2417.png" group-title="Развлекательные", Большая Азия HD (EDTV 576p)
http://188.113.190.15/215/tracks-v1a1/index.m3u8

#EXTINF:-1 tvg-id="521" tvg-logo="http://epg.one/img2/521.png" group-title="Познавательные",Viju Explore (EDTV 576p)
http://188.113.190.15/32/tracks-v1a1/index.m3u8

#EXTINF:-1 tvg-id="detsky" tvg-logo="https://epgx.site/p/unikum.png" group-title="Детские",Уникум (EDTV 576p)
http://188.113.190.15/41/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2239" tvg-logo="http://epg.one/img2/2239.png" group-title="Детские",СуперГерои(EDTV 576p)
http://188.113.190.15/162/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="9029" tvg-logo="https://epg.one/img2/9029.png" group-title="Детские",Baby Time(EDTV 576p)
http://188.113.190.15/178/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2027" tvg-logo="https://epg.one/img2/2027.png" group-title="Детские",В гостях у сказки (EDTV 576p)
http://188.113.190.15/43/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="284" tvg-logo="http://epg.one/img2/284.png" group-title="Детские",Мультимузыка(EDTV 576p)
http://188.113.190.15/145/tracks-v1a1/index.m3u8

#EXTINF:-1 tvg-id="2493" tvg-logo="http://epg.one/img2/2407.png" group-title="Кинозал",Киноман (EDTV 576p)
http://188.113.190.15/224/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="kinomiks" tvg-logo="https://epgx.site/p/kinomiks.png" group-title="Кинозал",Киномикс (EDTV 576p)
http://188.113.190.15/129/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="kinoxit" tvg-logo="https://epgx.site/p/kinoxit.png" group-title="Кинозал",Кинохит (WSVGA)
http://188.113.190.15/313/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id=".red" tvg-logo="http://epg.one/img2/311.png" group-title="Кинозал",.red HD
http://188.113.190.15/149/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="7314" tvg-logo="http://epg.one/img2/7314.png" group-title="Кинозал",Кинеко HD
http://188.113.190.15/156/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="431" tvg-logo="http://epg.one/img2/431.png" group-title="Кинозал",SHOT TV
http://188.113.190.15/166/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="dorama" tvg-logo="http://epg.one/img2/2174.png" group-title="Кинозал",Дорама (EDTV 576p)
http://188.113.190.15/233/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2493" tvg-logo="http://epg.one/img2/2493.png" group-title="Кинозал",Киноужас HD
http://188.113.190.15/323/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="2626" tvg-logo="http://epg.one/img2/2626.png" group-title="Кинозал",Բազմոց tv
http://stream01.vnet.am/Channel_118/mono.m3u8
#EXTINF:-1 tvg-id="nst" tvg-logo="https://epgx.site/p/nst.png" group-title="Кинозал",НСТ (EDTV 576p)
http://stream01.vnet.am/Channel_125/mono.m3u8
#EXTINF:-1 tvg-id="sony-tv" tvg-logo="https://epgx.site/p/sony.png" group-title="Кинозал",.red (EDTV 576p)
http://188.113.190.15/22/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="sony-scifi" tvg-logo="https://epgx.site/p/sony-scifi.png" group-title="Кинозал",.sci-fi (EDTV 576p)
http://188.113.190.15/23/tracks-v1a1/index.m3u8
#EXTINF:-1 audio-track="ru" tvg-id="tv1000-cee" tvg-logo="https://epgx.site/p/tv1000-cee.png" group-title="Кинозал",Viasat Kino (EDTV 576p)
http://81.7.108.21:9000/play/TV1000-DVBC322-sti4400017090089
#EXTINF:-1 tvg-id="komedijnoe-hd" tvg-logo="http://epg.one/img2/6240.png" group-title="Кинозал",START World
http://188.113.190.15/111/tracks-v1a1/index.m3u8
#EXTINF:-1 tvg-id="filmbox-arthouse" tvg-logo="https://epgx.site/p/filmbox-arthouse.png" group-title="Кинозал",Filmbox Arthouse (EDTV 576p)
http://188.113.190.15/207/mono.m3u8
#EXTINF:-1 tvg-id="kinokomedia" tvg-logo="https://epgx.site/p/kinokomedia.png" group-title="Кинозал",Кинокомедия (HD)

**Comment by smolnp** [comment]
спасибо

**Comment by mistrwest** [comment]
По ходу отваливаются периодически.  Видимо скорости потоков не хватает.  Понаблюдаю.

**Comment by mistrwest** [comment]
Обновлён список каналов.

**Comment by smolnp** [comment]
Спасибо! Посмотрю. Да, каналы периодически "отваливаются", одни чаще другие реже, стараюсь следить за теми, которые отваливаются реже, особенно летом... В зимний период меньше работы чаще обновляю плейлист. Спасибо за понимание.
