### ISSUE TITLE
Мой iptv плейлист не требующий обновления (25 телеканалов)

### ISSUE THREAD

**Issue by Monoloshka** [smolnp/IPTVru#2]
Мой iptv плейлист не требующий обновления.
Сперва я собрал 1 плейлист m3u из несколько скаченных и там вышло 10 000 каналов.
Потом я удалил нерабочие телеканалы и потом каждые год-полгода проверял работают ли ссылки и нерабочие убирал в итоге получилось у меня 25 телеканалов трансляции которых много лет работают по одной и той же ссылке.
[https://github.com/Monoloshka/iptv/blob/main/tv.m3u](https://github.com/Monoloshka/iptv/blob/main/tv.m3u)

**Comment by smolnp** [comment]
Спасибо! Я посмотрю, что из него можно взять.
