### ISSUE TITLE
Ошибка в теге ганала Nano

### ISSUE THREAD

**Issue by CaptainNemo-tut** [smolnp/IPTVru#39]
Что-то лишнее :)
#EXTINF:-1 tvg-id="nano-hd" nano-hd" tvg-logo="https://iptvx.one/picons/nano-hd.png" group-title="Познавательные",Нано (WSVGA)
Подозреваю, что второе nano-hd" с кавычкой. Отображается не верно в списке каналов

**Comment by smolnp** [comment]
Спасибо, исправлено
