### ISSUE TITLE
Познавательные каналы

### ISSUE THREAD

**Issue by shikulja** [smolnp/IPTVru#4]
history и history2, дискавери очень нужны, если будет возможность их добавить. Ну и возможно другие научно-образовательные.. про планеты.

**Comment by smolnp** [comment]
Discovery - доступен в обновлении, постараюсь своевременно его обновлять. 
"history и history2" в открытых источниках, либо тормозят, либо не работают, поэтому в ближайшее время не будут добавлены в плейлист. В качестве альтернативы могу предложить Viju History и История.
Про космос пока только Galaxy TV, ищу рабочую ссылку на Первый космический уже третью неделю.
Пока оставлю вопрос открытым
