### ISSUE TITLE
Потоки с http-referrer

### ISSUE THREAD

**Issue by ghost** [smolnp/IPTVru#59]
Возможно вы случайно удалили все потоки с http-referrer? Например тот же канал Победа
```
#EXTINF:-1 tvg-id="pobeda" tvg-logo="http://epg.one/img2/2447.png" group-title="Русский кинозал",Победа (HD ready)
#EXTVLCOPT:http-referrer=https://pobeda.tv/
https://pkvc-hls3.cdnvideo.ru/Pobeda/smil:Pobeda.smil/chunklist_b5128000_slru.m3u8
```
Либо ваш скрипт/программа которая проганяет весь плейлист не поддерживает http-referrer

**Comment by smolnp** [comment]
У Вас имеются ещё какие-либо потоки http-referrer?

**Comment by smolnp** [comment]
Скорее всего был, либо какой-то сбой, либо не поддерживал какой-нибудь плеер, сейчас уже не могу сказать...

**Comment by ghost** [comment]
Есть ещё такой хоть и глючный, но для проверки подойдёт
```
#EXTINF:-1 group-title="Русский кинозал",Победа
#EXTVLCOPT:http-referrer=https://televizor24tochka.ru/
https://streaming.skynetconnect.online/live/43-req_offset_28000000-req_window_0-1k_v5.m3u8
```

P.S. Остальные потоки с `http-referrer=https://peers.tv/` у меня открывались только с заглушкой:

![image](https://github.com/user-attachments/assets/039f9e0e-5094-431e-a59d-7f4684274599)

**Comment by smolnp** [comment]
зачем глючный? я уже первый добавил. Н другие каналы нет потоков?

**Comment by ghost** [comment]
> На другие каналы нет потоков?

На другие нет, можно закрывать
