### ISSUE TITLE
ТНТ

### ISSUE THREAD

**Issue by Fedosyk** [smolnp/IPTVru#6]
Почините пожалуйста ТНТ

**Comment by smolnp** [comment]
Уже исправил, сейчас обновляю плейлист, через пару часиков залью в сеть.

**Comment by smolnp** [comment]
У вас Россия 1 HD работает?

**Comment by Fedosyk** [comment]
Не идут оба...

**Comment by smolnp** [comment]
а теперь ТНТ (EDTV 576p), работает?

**Comment by Fedosyk** [comment]
Всё идёт, спасибо!
